# Site settings
title: canto alla durata
description: photos
baseurl: "/cad-photos" # the subpath of your site, e.g. /blog
url: "https://grammaton.github.io" # the base hostname & protocol for your site
author: "Giuseppe Silvi"

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/grammaton/
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
